-- Data Generation
use DairyFarm2

-- Unit
insert into Unit (name) values ('kg');
insert into Unit (name) values ('g');
insert into Unit (name) values ('l');
insert into Unit (name) values ('ml');
insert into Unit (name) values ('PKR');

-- ItemID
insert into ItemID (name) values ('Wheat');
insert into ItemID (name) values ('Corn');
insert into ItemID (name) values ('Maze');
insert into ItemID (name) values ('Barley');
insert into ItemID (name) values ('bentgrasses');
insert into ItemID (name) values ('sand bluestem');
insert into ItemID (name) values ('false oat-grass');
insert into ItemID (name) values ('Australian bluestem');
insert into ItemID (name) values ('hurricane grass');
insert into ItemID (name) values ( 'Clacium');
insert into ItemID (name) values ( 'Phosphorus');
insert into ItemID (name) values ( 'Magnesium');
insert into ItemID (name) values ( 'Med1');
insert into ItemID (name) values ( 'Med2');
insert into ItemID (name) values ( 'Med3');
insert into ItemID (name) values ( 'Milk');
insert into ItemID (name) values ( 'Meat');
insert into ItemID (name) values ('Agita 10 WG');
insert into ItemID (name) values ('Agita 10WG');
insert into ItemID (name) values ('Agita Fly Bait');
insert into ItemID (name) values ('Agri-Clean');
insert into ItemID (name) values ('Agri-Lube');
insert into ItemID (name) values ('Agrimycin 200');
insert into ItemID (name) values ('Agro-Clean');
insert into ItemID (name) values ('Airx 44 ACE');
insert into ItemID (name) values ('Airx 75');
insert into ItemID (name) values ('Airx 78 Plus');
insert into ItemID (name) values ('Hoof Care Gel');
insert into ItemID (name) values ('Hoof-it Liquid');
insert into ItemID (name) values ('Hoof-it Powder');
insert into ItemID (name) values ('Fast Cure Hoof-it Powder');
insert into ItemID (name) values ('Slow Cure HoofMax Dry');
insert into ItemID (name) values ('HoofMax Footbath Concentrate');
insert into ItemID (name) values ('Hy-Phos Concentrate');
insert into ItemID (name) values ('Hydra-Lyte');
insert into ItemID (name) values ('Quellaxcin 100');
insert into ItemID (name) values ('QuickBayt');
insert into ItemID (name) values ('QuickBlock+');
insert into ItemID (name) values ('Macrosyn Injectable Solution');
insert into ItemID (name) values ('MagLax Bolus');
insert into ItemID (name) values ('MagLax Powder');
insert into ItemID (name) values ('Magna Gel');
insert into ItemID (name) values ('Magna-Poultice');
insert into ItemID (name) values ('Magnalax Powder');
insert into ItemID (name) values ('MagnaPaste');
insert into ItemID (name) values ('Magnesium hydroxide Bolus');
insert into ItemID (name) values ('Magnesium Hydroxide Powder');
insert into ItemID (name) values ('Magnesium oxide Boluses');
insert into ItemID (name) values ('Gener-PYK');
insert into ItemID (name) values ('General Lube');
insert into ItemID (name) values ('General Lube (NS)');
insert into ItemID (name) values ('Generator B');
insert into ItemID (name) values ('Generator D');
insert into ItemID (name) values ('Generator Elite');
insert into ItemID (name) values ('Generator MB12');
insert into ItemID (name) values ('Generator Mill Pack');
insert into ItemID (name) values ('Generator ProSacc');
insert into ItemID (name) values ('Generator Ultra Feed Pack');
insert into ItemID (name) values ('Generator WS');
insert into ItemID (name) values ('Gentle Iodine 1%');
insert into ItemID (name) values ('KenoX5');
insert into ItemID (name) values ('Keraplex');
insert into ItemID (name) values ('Keto Amino Forte');
insert into ItemID (name) values ('Keto-Plex Forte');
insert into ItemID (name) values ('Ketofen');
insert into ItemID (name) values ('Ketoprofen V');
insert into ItemID (name) values ('Key-4 Plus');
insert into ItemID (name) values ('KeyPlex-842');
insert into ItemID (name) values ('KeyShure Calcium');
insert into ItemID (name) values ('KeyShure Cobalt');
insert into ItemID (name) values ('KeyShure Copper');
insert into ItemID (name) values ('KeyShure Iron');
insert into ItemID (name) values ('KeyShure Magnesium');
insert into ItemID (name) values ('KeyShure Manganese');
insert into ItemID (name) values ('KeyShure Zinc');
insert into ItemID (name) values ('KINETIC Vet ArmourGuard RTU');
insert into ItemID (name) values ('Kopper Kare');
insert into ItemID (name) values ('Koppersol');
insert into ItemID (name) values ('KuroGel');
insert into ItemID (name) values ('pennisetum');
insert into ItemID (name) values ('millet');
insert into ItemID (name) values ('lablab');
insert into ItemID (name) values ('cowpeas');
insert into ItemID (name) values ('soybeans');
insert into ItemID (name) values ('grain sorghum');
insert into ItemID (name) values ('Alocasia');
insert into ItemID (name) values ('Acacia');
insert into ItemID (name) values ('Alyce clover');
insert into ItemID (name) values ('Acalypha');
insert into ItemID (name) values ('American jointvetch');
insert into ItemID (name) values ('Acanthus');
insert into ItemID (name) values ('Andropogon');
insert into ItemID (name) values ('Achyranthes');
insert into ItemID (name) values ('Andropogon');
insert into ItemID (name) values ('Adenodolichos');
insert into ItemID (name) values ('Annatto');
insert into ItemID (name) values ('African birch');
insert into ItemID (name) values ('Antelope grass');
insert into ItemID (name) values ('African couch grass');
insert into ItemID (name) values ( 'Anthephora');
insert into ItemID (name) values ( 'African laburnum');
insert into ItemID (name) values ( 'Apple-ring acacia');
insert into ItemID (name) values ( 'African locust bean');
insert into ItemID (name) values ( 'Arizona cottontop');
insert into ItemID (name) values ( 'African sheepbush');
insert into ItemID (name) values ( 'Armgrass millet');
insert into ItemID (name) values ( 'Alfalfa');
insert into ItemID (name) values ( 'Bermudagrass');
insert into ItemID (name) values ( 'Clover Alsike');
insert into ItemID (name) values ( 'Clover Ladino');
insert into ItemID (name) values ( 'Clover Red');
insert into ItemID (name) values ( 'Clover White Dutch');
insert into ItemID (name) values ( 'Johnsongrass');
insert into ItemID (name) values ( 'Kentucky bluegrass');
insert into ItemID (name) values ( 'Lespedeza');
insert into ItemID (name) values ( 'Annual Lespedeza');
insert into ItemID (name) values ( 'Sericea');
insert into ItemID (name) values ( 'Orchardgrass');
insert into ItemID (name) values ( 'Pearl millet');
insert into ItemID (name) values ( 'Redtop');
insert into ItemID (name) values ( 'Reed canarygrass');
insert into ItemID (name) values ( 'Sudangrass');
insert into ItemID (name) values ( 'Tall fescue');
insert into ItemID (name) values ( 'Vetch');
insert into ItemID (name) values ( 'Crown Bluestem');
insert into ItemID (name) values ( 'Big Bluestem');
insert into ItemID (name) values ( 'Caucasian Bluestem');
insert into ItemID (name) values ( 'Little Indiangrass Ryegrass');
insert into ItemID (name) values ( 'Annual Soybean');
insert into ItemID (name) values ( 'Switchgrass');
insert into ItemID (name) values ( 'Triticale');
insert into ItemID (name) values ( 'Turnip');
insert into ItemID (name) values ( 'Forage Vetch');
insert into ItemID (name) values ( 'Hairy Canola/Rapeseed');
insert into ItemID (name) values ( 'Chickpea');
insert into ItemID (name) values ( 'Kura');
insert into ItemID (name) values ( 'Crabgrass');
insert into ItemID (name) values ( 'Kenaf');
insert into ItemID (name) values ( 'Lupin');
insert into ItemID (name) values ( 'Pigeonpea');
insert into ItemID (name) values ( 'Selenium');
insert into ItemID (name) values ( 'Vitamin A');
insert into ItemID (name) values ( 'Vitamin D');
insert into ItemID (name) values ( 'Vitamin E');


-- unit_id 5 is of Rs. which is not right for suppliments, medicine, but it is reserved for Expenses or is bought table. Idk right now how to eliminate this on auto data generation.
-- Price
insert into Price (item_id, price, date_of_price, unit_id) values (1, 97.79, '5/19/2021',  1);
insert into Price (item_id, price, date_of_price, unit_id) values (2, 66.53, '5/24/2021',  2);
insert into Price (item_id, price, date_of_price, unit_id) values (3, 16.75, '12/2/2020',  3);
insert into Price (item_id, price, date_of_price, unit_id) values (4, 37.93, '12/31/2020', 4);
insert into Price (item_id, price, date_of_price, unit_id) values (5, 16.29, '2/27/2021',  5);
insert into Price (item_id, price, date_of_price, unit_id) values (6, 27.87, '1/31/2021',  1);
insert into Price (item_id, price, date_of_price, unit_id) values (7, 46.87, '2/23/2021',  2);
insert into Price (item_id, price, date_of_price, unit_id) values (8, 91.21, '6/23/2021',  3);
insert into Price (item_id, price, date_of_price, unit_id) values (9, 50.09, '4/27/2021',  4);
insert into Price (item_id, price, date_of_price, unit_id) values (10, 54.2, '6/25/2020',  5);
insert into Price (item_id, price, date_of_price, unit_id) values (11, 19.92, '3/15/2021', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (12, 16.58, '7/5/2021',  2);
insert into Price (item_id, price, date_of_price, unit_id) values (13, 34.2, '12/8/2020',  3);
insert into Price (item_id, price, date_of_price, unit_id) values (14, 29.94, '2/13/2021', 4);
insert into Price (item_id, price, date_of_price, unit_id) values (15, 61.67, '3/30/2021', 5);
insert into Price (item_id, price, date_of_price, unit_id) values (16, 58.46, '5/3/2021',  1);
insert into Price (item_id, price, date_of_price, unit_id) values (17, 61.46, '5/18/2020', 2);
insert into Price (item_id, price, date_of_price, unit_id) values (18, 76.21, '3/8/2021',  3);
insert into Price (item_id, price, date_of_price, unit_id) values (19, 13.61, '5/16/2021', 4);
insert into Price (item_id, price, date_of_price, unit_id) values (20, 47.1, '1/22/2021',  5);
insert into Price (item_id, price, date_of_price, unit_id) values (21, 35.45, '10/26/2020',1);
insert into Price (item_id, price, date_of_price, unit_id) values (22, 79.64, '7/21/2020', 2);
insert into Price (item_id, price, date_of_price, unit_id) values (23, 14.89, '8/14/2020', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (24, 28.84, '6/2/2021',  4);
insert into Price (item_id, price, date_of_price, unit_id) values (25, 74.73, '8/21/2020', 5);
insert into Price (item_id, price, date_of_price, unit_id) values (26, 82.44, '6/10/2021', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (27, 46.28, '5/21/2020', 2);
insert into Price (item_id, price, date_of_price, unit_id) values (28, 20.39, '4/22/2021', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (29, 73.38, '6/26/2021', 4);
insert into Price (item_id, price, date_of_price, unit_id) values (30, 19.89, '1/31/2021', 5);
insert into Price (item_id, price, date_of_price, unit_id) values (31, 51.88, '1/22/2021', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (32, 69.52, '9/27/2020', 2);
insert into Price (item_id, price, date_of_price, unit_id) values (33, 79.2, '7/23/2021',  3);
insert into Price (item_id, price, date_of_price, unit_id) values (34, 72.41, '11/19/2020',4);
insert into Price (item_id, price, date_of_price, unit_id) values (35, 72.94, '6/5/2021',  5);
insert into Price (item_id, price, date_of_price, unit_id) values (36, 47.47, '2/15/2021', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (37, 80.5, '7/31/2020',  2);
insert into Price (item_id, price, date_of_price, unit_id) values (38, 89.7, '7/27/2021',  3);
insert into Price (item_id, price, date_of_price, unit_id) values (39, 56.73, '10/30/2020',4);
insert into Price (item_id, price, date_of_price, unit_id) values (40, 36.79, '5/27/2020', 5);
insert into Price (item_id, price, date_of_price, unit_id) values (41, 20.4, '12/27/2020', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (42, 98.25, '3/17/2021', 2);
insert into Price (item_id, price, date_of_price, unit_id) values (43, 51.7, '11/20/2020', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (44, 96.3, '10/24/2020', 4);
insert into Price (item_id, price, date_of_price, unit_id) values (45, 52.83, '3/31/2021', 5);
insert into Price (item_id, price, date_of_price, unit_id) values (46, 57.67, '6/23/2021', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (47, 88.8, '3/7/2021',   2);
insert into Price (item_id, price, date_of_price, unit_id) values (48, 39.55, '9/12/2020', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (49, 32.85, '7/21/2020', 4);
insert into Price (item_id, price, date_of_price, unit_id) values (50, 84.71, '8/10/2020', 5);
insert into Price (item_id, price, date_of_price, unit_id) values (51, 67.96, '1/12/2021', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (52, 94.22, '5/6/2021',  2);
insert into Price (item_id, price, date_of_price, unit_id) values (53, 37.24, '1/30/2021', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (54, 79.3, '1/30/2021',  4);
insert into Price (item_id, price, date_of_price, unit_id) values (55, 91.53, '11/29/2020',5);
insert into Price (item_id, price, date_of_price, unit_id) values (56, 93.21, '12/6/2020', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (57, 40.53, '5/12/2021', 2);
insert into Price (item_id, price, date_of_price, unit_id) values (58, 48.16, '8/12/2020', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (59, 73.82, '2/8/2021',  4);
insert into Price (item_id, price, date_of_price, unit_id) values (60, 81.49, '10/24/2020',5);
insert into Price (item_id, price, date_of_price, unit_id) values (61, 86.11, '11/1/2020', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (62, 26.43, '5/11/2021', 2);
insert into Price (item_id, price, date_of_price, unit_id) values (63, 33.59, '4/20/2021', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (64, 32.0, '8/5/2020',   4);
insert into Price (item_id, price, date_of_price, unit_id) values (65, 49.53, '11/2/2020', 5);
insert into Price (item_id, price, date_of_price, unit_id) values (66, 72.21, '12/8/2020', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (67, 17.2, '6/13/2021',  2);
insert into Price (item_id, price, date_of_price, unit_id) values (68, 42.8, '10/26/2020', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (69, 15.94, '6/17/2020', 4);
insert into Price (item_id, price, date_of_price, unit_id) values (70, 65.95, '6/27/2021', 5);
insert into Price (item_id, price, date_of_price, unit_id) values (71, 45.97, '3/8/2021',  1);
insert into Price (item_id, price, date_of_price, unit_id) values (72, 51.89, '7/2/2021',  2);
insert into Price (item_id, price, date_of_price, unit_id) values (73, 59.14, '7/3/2021',  3);
insert into Price (item_id, price, date_of_price, unit_id) values (74, 87.95, '10/4/2020', 4);
insert into Price (item_id, price, date_of_price, unit_id) values (75, 31.48, '5/22/2020', 5);
insert into Price (item_id, price, date_of_price, unit_id) values (76, 61.67, '3/15/2021', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (77, 81.91, '5/23/2020', 2);
insert into Price (item_id, price, date_of_price, unit_id) values (78, 31.04, '7/17/2020', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (79, 13.76, '11/24/2020',4);
insert into Price (item_id, price, date_of_price, unit_id) values (80, 82.91, '6/24/2020', 5);
insert into Price (item_id, price, date_of_price, unit_id) values (81, 22.44, '6/1/2020',  1);
insert into Price (item_id, price, date_of_price, unit_id) values (82, 25.54, '10/16/2020',2);
insert into Price (item_id, price, date_of_price, unit_id) values (83, 29.16, '7/25/2021', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (84, 67.1, '11/5/2020',  4);
insert into Price (item_id, price, date_of_price, unit_id) values (85, 46.83, '6/23/2021', 5);
insert into Price (item_id, price, date_of_price, unit_id) values (86, 34.52, '8/20/2020', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (87, 74.97, '4/22/2021', 2);
insert into Price (item_id, price, date_of_price, unit_id) values (88, 59.8, '5/11/2020',  3);
insert into Price (item_id, price, date_of_price, unit_id) values (89, 55.91, '7/20/2020', 4);
insert into Price (item_id, price, date_of_price, unit_id) values (90, 52.21, '1/19/2021', 5);
insert into Price (item_id, price, date_of_price, unit_id) values (91, 87.65, '5/24/2020', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (92, 92.25, '11/22/2020',2);
insert into Price (item_id, price, date_of_price, unit_id) values (93, 48.53, '9/29/2020', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (94, 88.72, '1/19/2021', 4);
insert into Price (item_id, price, date_of_price, unit_id) values (95, 46.63, '6/12/2021', 5);
insert into Price (item_id, price, date_of_price, unit_id) values (96, 11.6, '5/12/2021',  1);
insert into Price (item_id, price, date_of_price, unit_id) values (97, 46.28, '12/3/2020', 2);
insert into Price (item_id, price, date_of_price, unit_id) values (98, 10.79, '4/25/2021', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (99, 21.76, '12/5/2020', 4);
insert into Price (item_id, price, date_of_price, unit_id) values (100, 47.74, '2/3/2021', 5);
insert into Price (item_id, price, date_of_price, unit_id) values (101, 47.47, '12/3/2020',1);
insert into Price (item_id, price, date_of_price, unit_id) values (102, 73.41, '6/2/2020', 2);
insert into Price (item_id, price, date_of_price, unit_id) values (103, 66.22,'10/16/2020',3);
insert into Price (item_id, price, date_of_price, unit_id) values (104, 39.23,'12/26/2020',4);
insert into Price (item_id, price, date_of_price, unit_id) values (105, 13.29,'11/11/2020',5);
insert into Price (item_id, price, date_of_price, unit_id) values (106, 15.79,'8/29/2020', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (107, 20.55,'12/20/2020',2);
insert into Price (item_id, price, date_of_price, unit_id) values (108, 53.4, '6/29/2020', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (109, 17.63, '6/18/2021',4);
insert into Price (item_id, price, date_of_price, unit_id) values (110, 74.38,'10/19/2020',5);
insert into Price (item_id, price, date_of_price, unit_id) values (111, 85.78, '3/29/2021',1);
insert into Price (item_id, price, date_of_price, unit_id) values (112, 32.5, '9/17/2020', 2);
insert into Price (item_id, price, date_of_price, unit_id) values (113, 77.93, '4/3/2021', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (114, 39.58,'11/12/2020',4);
insert into Price (item_id, price, date_of_price, unit_id) values (115, 60.77, '7/31/2020',5);
insert into Price (item_id, price, date_of_price, unit_id) values (116, 60.14, '3/3/2021', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (117, 70.76, '10/1/2020',2);
insert into Price (item_id, price, date_of_price, unit_id) values (118, 80.42, '5/17/2020',3);
insert into Price (item_id, price, date_of_price, unit_id) values (119, 19.67, '9/6/2020', 4);
insert into Price (item_id, price, date_of_price, unit_id) values (120, 97.64, '4/5/2021', 5);
insert into Price (item_id, price, date_of_price, unit_id) values (121, 50.79, '6/5/2020', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (122, 42.57, '5/16/2020',2);
insert into Price (item_id, price, date_of_price, unit_id) values (123, 89.44, '9/19/2020',3);
insert into Price (item_id, price, date_of_price, unit_id) values (124, 24.01, '5/28/2020',4);
insert into Price (item_id, price, date_of_price, unit_id) values (125, 64.69, '7/8/2021', 5);
insert into Price (item_id, price, date_of_price, unit_id) values (126, 22.71,'12/29/2020',1);
insert into Price (item_id, price, date_of_price, unit_id) values (127, 33.96, '6/6/2021', 2);
insert into Price (item_id, price, date_of_price, unit_id) values (128, 54.77, '4/3/2021', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (129, 49.27, '9/19/2020',4);
insert into Price (item_id, price, date_of_price, unit_id) values (130, 84.25, '3/1/2021', 5);
insert into Price (item_id, price, date_of_price, unit_id) values (131, 58.21, '5/27/2020',1);
insert into Price (item_id, price, date_of_price, unit_id) values (132, 58.78, '11/3/2020',2);
insert into Price (item_id, price, date_of_price, unit_id) values (133, 25.57, '6/29/2020',3);
insert into Price (item_id, price, date_of_price, unit_id) values (134, 83.68, '5/27/2020',4);
insert into Price (item_id, price, date_of_price, unit_id) values (135, 48.87, '5/16/2021',5);
insert into Price (item_id, price, date_of_price, unit_id) values (136, 96.7, '6/12/2020', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (137, 26.62, '7/2/2021', 2);
insert into Price (item_id, price, date_of_price, unit_id) values (138, 57.64, '7/26/2021',3);
insert into Price (item_id, price, date_of_price, unit_id) values (139, 62.11, '7/25/2020',4);
insert into Price (item_id, price, date_of_price, unit_id) values (140, 40.82, '5/14/2021',5);
insert into Price (item_id, price, date_of_price, unit_id) values (1, 83.18, '10/28/2020', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (2, 17.46, '1/21/2021',  2);
insert into Price (item_id, price, date_of_price, unit_id) values (3, 22.33, '12/14/2020', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (4, 78.71, '1/29/2021',  4);
insert into Price (item_id, price, date_of_price, unit_id) values (5, 94.83, '3/11/2021',  5);
insert into Price (item_id, price, date_of_price, unit_id) values (6, 73.06, '6/30/2021',  1);
insert into Price (item_id, price, date_of_price, unit_id) values (7, 54.39, '8/3/2021',   2);
insert into Price (item_id, price, date_of_price, unit_id) values (8, 13.76, '8/26/2020',  3);
insert into Price (item_id, price, date_of_price, unit_id) values (9, 37.44, '9/2/2020',   4);
insert into Price (item_id, price, date_of_price, unit_id) values (10, 14.0, '6/27/2020',  5);
insert into Price (item_id, price, date_of_price, unit_id) values (11, 50.8, '9/21/2020',  1);
insert into Price (item_id, price, date_of_price, unit_id) values (12, 38.06, '4/25/2021', 2);
insert into Price (item_id, price, date_of_price, unit_id) values (13, 39.85, '2/21/2021', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (14, 83.88, '5/9/2020',  4);
insert into Price (item_id, price, date_of_price, unit_id) values (15, 76.76, '3/7/2021',  5);
insert into Price (item_id, price, date_of_price, unit_id) values (16, 96.45, '9/11/2020', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (17, 80.66, '7/4/2021',  2);
insert into Price (item_id, price, date_of_price, unit_id) values (18, 17.89, '11/10/2020',3);
insert into Price (item_id, price, date_of_price, unit_id) values (19, 10.24, '6/3/2021',  4);
insert into Price (item_id, price, date_of_price, unit_id) values (20, 96.28, '8/23/2020', 5);
insert into Price (item_id, price, date_of_price, unit_id) values (21, 36.63, '5/2/2021',  1);
insert into Price (item_id, price, date_of_price, unit_id) values (22, 91.31, '3/26/2021', 2);
insert into Price (item_id, price, date_of_price, unit_id) values (23, 49.66, '10/31/2020',3);
insert into Price (item_id, price, date_of_price, unit_id) values (24, 74.13, '5/12/2021', 4);
insert into Price (item_id, price, date_of_price, unit_id) values (25, 71.76, '7/13/2021', 5);
insert into Price (item_id, price, date_of_price, unit_id) values (26, 22.55, '10/30/2020',1);
insert into Price (item_id, price, date_of_price, unit_id) values (27, 24.87, '7/31/2020', 2);
insert into Price (item_id, price, date_of_price, unit_id) values (28, 10.82, '7/1/2021',  3);
insert into Price (item_id, price, date_of_price, unit_id) values (29, 41.8, '6/27/2020',  4);
insert into Price (item_id, price, date_of_price, unit_id) values (30, 23.6, '8/15/2020',  5);
insert into Price (item_id, price, date_of_price, unit_id) values (31, 48.97, '12/23/2020',1);
insert into Price (item_id, price, date_of_price, unit_id) values (32, 84.2, '5/1/2021',   2);
insert into Price (item_id, price, date_of_price, unit_id) values (33, 89.13, '3/3/2021',  3);
insert into Price (item_id, price, date_of_price, unit_id) values (34, 75.38, '7/7/2021',  4);
insert into Price (item_id, price, date_of_price, unit_id) values (35, 94.25, '5/7/2021',  5);
insert into Price (item_id, price, date_of_price, unit_id) values (36, 65.52, '5/25/2021', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (37, 62.6, '5/20/2020',  2);
insert into Price (item_id, price, date_of_price, unit_id) values (38, 66.94, '5/29/2020', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (39, 45.28, '5/31/2021', 4);
insert into Price (item_id, price, date_of_price, unit_id) values (40, 60.36, '3/3/2021',  5);
insert into Price (item_id, price, date_of_price, unit_id) values (41, 37.16, '3/26/2021', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (42, 36.21, '7/5/2021',  2);
insert into Price (item_id, price, date_of_price, unit_id) values (43, 95.18, '5/1/2021',  3);
insert into Price (item_id, price, date_of_price, unit_id) values (44, 94.85, '6/8/2021',  4);
insert into Price (item_id, price, date_of_price, unit_id) values (45, 49.35, '2/4/2021',  5);
insert into Price (item_id, price, date_of_price, unit_id) values (46, 94.32, '8/26/2020', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (47, 34.18, '5/8/2020',  2);
insert into Price (item_id, price, date_of_price, unit_id) values (48, 85.95, '4/13/2021', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (49, 92.37, '6/5/2020',  4);
insert into Price (item_id, price, date_of_price, unit_id) values (50, 99.19, '8/5/2021',  5);
insert into Price (item_id, price, date_of_price, unit_id) values (51, 32.77, '4/30/2021', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (52, 15.55, '6/8/2020',  2);
insert into Price (item_id, price, date_of_price, unit_id) values (53, 19.78, '6/10/2021', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (54, 21.74, '6/5/2021',  4);
insert into Price (item_id, price, date_of_price, unit_id) values (55, 63.63, '5/6/2020',  5);
insert into Price (item_id, price, date_of_price, unit_id) values (56, 75.38, '7/20/2020', 1);
insert into Price (item_id, price, date_of_price, unit_id) values (57, 89.98, '2/10/2021', 2);
insert into Price (item_id, price, date_of_price, unit_id) values (58, 75.58, '1/11/2021', 3);
insert into Price (item_id, price, date_of_price, unit_id) values (59, 32.72, '5/30/2021', 4);
insert into Price (item_id, price, date_of_price, unit_id) values (60, 73.05, '2/15/2021', 5);


-- FoodGroupID
insert into FoodGroupID (id) values ('G1'); --COW
insert into FoodGroupID (id) values ('G2'); --BUFFALO
insert into FoodGroupID (id) values ('G3'); --SHEEP

-- FoodGroup
insert into FoodGroup (id, group_name, ing_id) values ('G1', 'A', 'G1');
insert into FoodGroup (id, group_name, ing_id) values ('G2', 'B', 'G2');
insert into FoodGroup (id, group_name, ing_id) values ('G3', 'C', 'G3');

-- IngredientData
insert into IngredientData (fgroup_id, item_id, weight) values ('G2', '7', 70.06);
insert into IngredientData (fgroup_id, item_id, weight) values ('G3', '10', 34.52);
insert into IngredientData (fgroup_id, item_id, weight) values ('G1', '6', 44.78);
insert into IngredientData (fgroup_id, item_id, weight) values ('G2', '8', 25.52);
insert into IngredientData (fgroup_id, item_id, weight) values ('G3', '5', 23.58);
insert into IngredientData (fgroup_id, item_id, weight) values ('G1', '4', 14.61);
insert into IngredientData (fgroup_id, item_id, weight) values ('G1', '1', 15.52);
insert into IngredientData (fgroup_id, item_id, weight) values ('G3', '9', 97.71);
insert into IngredientData (fgroup_id, item_id, weight) values ('G2', '11', 25.09);
insert into IngredientData (fgroup_id, item_id, weight) values ('G2', '2', 94.64);

---------------------------------------------------------------------------------------------------------------------------------




-- ForageType -- make sure item_id is correct and cross check it from ItemID table.
insert into ForageType (item_id, name) values (1, 'Wheat');
insert into ForageType (item_id, name) values (2, 'Corn');
insert into ForageType (item_id, name) values (3, 'Maze');
insert into ForageType (item_id, name) values (4, 'Barley');
insert into ForageType (item_id, name) values (5, 'bentgrasses');
insert into ForageType (item_id, name) values (6, 'sand bluestem');
insert into ForageType (item_id, name) values (7, 'false oat-grass');
insert into ForageType (item_id, name) values (8, 'Australian bluestem');
insert into ForageType (item_id, name) values (9, 'hurricane grass');



insert into ForageType (item_id, name) values (1, 'Wheat');
insert into ForageType (item_id, name) values (2, 'Corn');
insert into ForageType (item_id, name) values (3, 'Maze');
insert into ForageType (item_id, name) values (4, 'Barley');
insert into ForageType (item_id, name) values (5, 'bentgrasses');
insert into ForageType (item_id, name) values (6, 'sand bluestem');
insert into ForageType (item_id, name) values (7, 'false oat-grass');
insert into ForageType (item_id, name) values (8, 'Australian bluestem');
insert into ForageType (item_id, name) values (9, 'hurricane grass');
insert into ForageType (item_id, name) values (10, 'Clacium');
insert into ForageType (item_id, name) values (11, 'Phosphorus');
insert into ForageType (item_id, name) values (12, 'Magnesium');
insert into ForageType (item_id, name) values (80, 'pennisetum');
insert into ForageType (item_id, name) values (81, 'millet');
insert into ForageType (item_id, name) values (82, 'lablab');
insert into ForageType (item_id, name) values (83, 'cowpeas');
insert into ForageType (item_id, name) values (84, 'soybeans');
insert into ForageType (item_id, name) values (85, 'grain sorghum');
insert into ForageType (item_id, name) values (86, 'Alocasia');
insert into ForageType (item_id, name) values (87, 'Acacia');
insert into ForageType (item_id, name) values (88, 'Alyce clover');
insert into ForageType (item_id, name) values (89, 'Acalypha');
insert into ForageType (item_id, name) values (90, 'American jointvetch');
insert into ForageType (item_id, name) values (91, 'Acanthus');
insert into ForageType (item_id, name) values (92, 'Andropogon');
insert into ForageType (item_id, name) values (93, 'Achyranthes');
insert into ForageType (item_id, name) values (94, 'Andropogon');
insert into ForageType (item_id, name) values (95, 'Adenodolichos');
insert into ForageType (item_id, name) values (96, 'Annatto');
insert into ForageType (item_id, name) values (97, 'African birch');
insert into ForageType (item_id, name) values (98, 'Antelope grass');
insert into ForageType (item_id, name) values (99, 'African couch grass');
insert into ForageType (item_id, name) values (100, 'Anthephora');
insert into ForageType (item_id, name) values (101, 'African laburnum');
insert into ForageType (item_id, name) values (102, 'Apple-ring acacia');
insert into ForageType (item_id, name) values (103, 'African locust bean');
insert into ForageType (item_id, name) values (104, 'Arizona cottontop');
insert into ForageType (item_id, name) values (105, 'African sheepbush');
insert into ForageType (item_id, name) values (106, 'Armgrass millet');
insert into ForageType (item_id, name) values (107, 'Alfalfa');
insert into ForageType (item_id, name) values (108, 'Bermudagrass');
insert into ForageType (item_id, name) values (109, 'Clover Alsike');
insert into ForageType (item_id, name) values (110, 'Clover Ladino');
insert into ForageType (item_id, name) values (111, 'Clover Red');
insert into ForageType (item_id, name) values (112, 'Clover White Dutch');
insert into ForageType (item_id, name) values (113, 'Johnsongrass');
insert into ForageType (item_id, name) values (114, 'Kentucky bluegrass');
insert into ForageType (item_id, name) values (115, 'Lespedeza');
insert into ForageType (item_id, name) values (116, 'Annual Lespedeza');
insert into ForageType (item_id, name) values (117, 'Sericea');
insert into ForageType (item_id, name) values (118, 'Orchardgrass');
insert into ForageType (item_id, name) values (119, 'Pearl millet');
insert into ForageType (item_id, name) values (120, 'Redtop');
insert into ForageType (item_id, name) values (121, 'Reed canarygrass');
insert into ForageType (item_id, name) values (122, 'Sudangrass');
insert into ForageType (item_id, name) values (123, 'Tall fescue');
insert into ForageType (item_id, name) values (124, 'Vetch');
insert into ForageType (item_id, name) values (125, 'Crown Bluestem');
insert into ForageType (item_id, name) values (126, 'Big Bluestem');
insert into ForageType (item_id, name) values (127, 'Caucasian Bluestem');
insert into ForageType (item_id, name) values (128, 'Little Indiangrass Ryegrass');
insert into ForageType (item_id, name) values (129, 'Annual Soybean');
insert into ForageType (item_id, name) values (130, 'Switchgrass');
insert into ForageType (item_id, name) values (131, 'Triticale');
insert into ForageType (item_id, name) values (132, 'Turnip');
insert into ForageType (item_id, name) values (133, 'Forage Vetch');
insert into ForageType (item_id, name) values (134, 'Hairy Canola/Rapeseed');
insert into ForageType (item_id, name) values (135, 'Chickpea');
insert into ForageType (item_id, name) values (136, 'Kura');
insert into ForageType (item_id, name) values (137, 'Crabgrass');
insert into ForageType (item_id, name) values (138, 'Kenaf');
insert into ForageType (item_id, name) values (139, 'Lupin');
insert into ForageType (item_id, name) values (140, 'Pigeonpea');
insert into ForageType (item_id, name) values (141, 'Selenium');
insert into ForageType (item_id, name) values (142, 'Vitamin A');
insert into ForageType (item_id, name) values (143, 'Vitamin D');
insert into ForageType (item_id, name) values (144, 'Vitamin E');



-- Forage -- cross check units from unit table and also type_id from the ForageType after changes in ForageType
insert into Forage (type_id, quantity, m_unit_id, purchase_date) values (1, 27, 1, '6/6/2020');
insert into Forage (type_id, quantity, m_unit_id, purchase_date) values (2, 43, 1, '6/6/2020');
insert into Forage (type_id, quantity, m_unit_id, purchase_date) values (3, 64, 1, '6/6/2020');
insert into Forage (type_id, quantity, m_unit_id, purchase_date) values (4, 5, 1, '6/6/2020');
insert into Forage (type_id, quantity, m_unit_id, purchase_date) values (5, 9, 1, '6/6/2020');
insert into Forage (type_id, quantity, m_unit_id, purchase_date) values (6, 28, 1, '6/6/2020');
insert into Forage (type_id, quantity, m_unit_id, purchase_date) values (7, 52, 1, '6/6/2020');
insert into Forage (type_id, quantity, m_unit_id, purchase_date) values (8, 28, 1, '6/6/2020');
insert into Forage (type_id, quantity, m_unit_id, purchase_date) values (9, 68, 1, '6/6/2020');
insert into Forage (type_id, quantity, m_unit_id, purchase_date) values ( 1, 8, 1, '6/7/2020');
insert into Forage (type_id, quantity, m_unit_id, purchase_date) values ( 2, 13, 1, '6/7/2020');
insert into Forage (type_id, quantity, m_unit_id, purchase_date) values ( 3, 69, 1, '6/7/2020');
insert into Forage (type_id, quantity, m_unit_id, purchase_date) values ( 4, 23, 1, '6/7/2020');
insert into Forage (type_id, quantity, m_unit_id, purchase_date) values ( 5, 80, 1, '6/7/2020');
insert into Forage (type_id, quantity, m_unit_id, purchase_date) values ( 6, 95, 1, '6/7/2020');
insert into Forage (type_id, quantity, m_unit_id, purchase_date) values ( 7, 65, 1, '6/7/2020');
insert into Forage (type_id, quantity, m_unit_id, purchase_date) values ( 8, 32, 1, '6/7/2020');
insert into Forage (type_id, quantity, m_unit_id, purchase_date) values ( 9, 22, 1, '6/7/2020');

-- SupplimentType

insert into SupplimentType (item_id, name) values (10, 'Clacium');
insert into SupplimentType (item_id, name) values (11, 'Phosphorus');
insert into SupplimentType (item_id, name) values (12, 'Magnesium');

-- Suppliment 
insert into Suppliment (type_id, quantity, m_unit_id, purchase_date) values (1, 10, 2, '6/7/2020');
insert into Suppliment (type_id, quantity, m_unit_id, purchase_date) values (2, 1, 2, '6/7/2020');
insert into Suppliment (type_id, quantity, m_unit_id, purchase_date) values (3, 8, 1, '6/7/2020');
insert into Suppliment (type_id, quantity, m_unit_id, purchase_date) values (1, 2, 2, '6/6/2020');
insert into Suppliment (type_id, quantity, m_unit_id, purchase_date) values (2, 8, 2, '6/6/2020');
insert into Suppliment (type_id, quantity, m_unit_id, purchase_date) values (3, 10, 1, '6/6/2020');

-- MedicineType
insert into MedicineType (item_id, name) values (13, 'QuickBlock+');
insert into MedicineType (item_id, name) values (14, 'Magna Gel');
insert into MedicineType (item_id, name) values (15, 'Gener-PYK');
insert into MedicineType (item_id, name) values (18, 'Agita 10 WG');
insert into MedicineType (item_id, name) values (19, 'Agita 10WG');
insert into MedicineType (item_id, name) values (20, 'Agita Fly Bait');
insert into MedicineType (item_id, name) values (21, 'Agri-Clean');
insert into MedicineType (item_id, name) values (22, 'Agri-Lube');
insert into MedicineType (item_id, name) values (23, 'Agrimycin 200');
insert into MedicineType (item_id, name) values (24, 'Agro-Clean');
insert into MedicineType (item_id, name) values (25, 'Airx 44 ACE');
insert into MedicineType (item_id, name) values (26, 'Airx 75');
insert into MedicineType (item_id, name) values (27, 'Airx 78 Plus');
insert into MedicineType (item_id, name) values (28, 'Hoof Care Gel');
insert into MedicineType (item_id, name) values (29, 'Hoof-it Liquid');
insert into MedicineType (item_id, name) values (30, 'Hoof-it Powder');
insert into MedicineType (item_id, name) values (31, 'Fast Cure Hoof-it Powder');
insert into MedicineType (item_id, name) values (32, 'Slow Cure HoofMax Dry');
insert into MedicineType (item_id, name) values (33, 'HoofMax Footbath Concentrate');
insert into MedicineType (item_id, name) values (34, 'Hy-Phos Concentrate');
insert into MedicineType (item_id, name) values (35, 'Hydra-Lyte');
insert into MedicineType (item_id, name) values (36, 'Quellaxcin 100');
insert into MedicineType (item_id, name) values (37, 'QuickBayt');
insert into MedicineType (item_id, name) values (38, 'QuickBlock+');
insert into MedicineType (item_id, name) values (39, 'Macrosyn Injectable Solution');
insert into MedicineType (item_id, name) values (40, 'MagLax Bolus');
insert into MedicineType (item_id, name) values (41, 'MagLax Powder');
insert into MedicineType (item_id, name) values (42, 'Magna Gel');
insert into MedicineType (item_id, name) values (43, 'Magna-Poultice');
insert into MedicineType (item_id, name) values (44, 'Magnalax Powder');
insert into MedicineType (item_id, name) values (45, 'MagnaPaste');
insert into MedicineType (item_id, name) values (46, 'Magnesium hydroxide Bolus');
insert into MedicineType (item_id, name) values (47, 'Magnesium Hydroxide Powder');
insert into MedicineType (item_id, name) values (48, 'Magnesium oxide Boluses');
insert into MedicineType (item_id, name) values (49, 'Gener-PYK');
insert into MedicineType (item_id, name) values (50, 'General Lube');
insert into MedicineType (item_id, name) values (51, 'General Lube (NS)');
insert into MedicineType (item_id, name) values (52, 'Generator B');
insert into MedicineType (item_id, name) values (53, 'Generator D');
insert into MedicineType (item_id, name) values (54, 'Generator Elite');
insert into MedicineType (item_id, name) values (55, 'Generator MB12');
insert into MedicineType (item_id, name) values (56, 'Generator Mill Pack');
insert into MedicineType (item_id, name) values (57, 'Generator ProSacc');
insert into MedicineType (item_id, name) values (58, 'Generator Ultra Feed Pack');
insert into MedicineType (item_id, name) values (59, 'Generator WS');
insert into MedicineType (item_id, name) values (60, 'Gentle Iodine 1%');
insert into MedicineType (item_id, name) values (61, 'KenoX5');
insert into MedicineType (item_id, name) values (62, 'Keraplex');
insert into MedicineType (item_id, name) values (63, 'Keto Amino Forte');
insert into MedicineType (item_id, name) values (64, 'Keto-Plex Forte');
insert into MedicineType (item_id, name) values (65, 'Ketofen');
insert into MedicineType (item_id, name) values (66, 'Ketoprofen V');
insert into MedicineType (item_id, name) values (67, 'Key-4 Plus');
insert into MedicineType (item_id, name) values (68, 'KeyPlex-842');
insert into MedicineType (item_id, name) values (69, 'KeyShure Calcium');
insert into MedicineType (item_id, name) values (70, 'KeyShure Cobalt');
insert into MedicineType (item_id, name) values (71, 'KeyShure Copper');
insert into MedicineType (item_id, name) values (72, 'KeyShure Iron');
insert into MedicineType (item_id, name) values (73, 'KeyShure Magnesium');
insert into MedicineType (item_id, name) values (74, 'KeyShure Manganese');
insert into MedicineType (item_id, name) values (75, 'KeyShure Zinc');
insert into MedicineType (item_id, name) values (76, 'KINETIC Vet ArmourGuard RTU');
insert into MedicineType (item_id, name) values (77, 'Kopper Kare');
insert into MedicineType (item_id, name) values (78, 'Koppersol');
insert into MedicineType (item_id, name) values (79, 'KuroGel');

-- Medicine -- multiple records with different price and date of purchase
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (1, 23.39, 3, '6/7/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (2, 28.63, 4, '6/7/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (3, 24.13, 4, '6/7/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (1, 19.34, 3, '6/6/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (2, 38.04, 4, '6/6/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (3, 71.0, 4, '6/6/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (2, 71.0, 4, '7/13/2015');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (1, 71.0, 3, '1/10/2016');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (1, 7.13, 3,'8/5/2017');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (1, 5.32, 3,'5/15/2018');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (1, 16.19, 3, '1/29/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (2, 28.36, 3, '1/22/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (3, 44.67, 4, '1/23/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (4, 32.86, 4, '1/23/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (5, 34.46, 3, '1/19/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (6, 30.73, 4, '1/10/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (7, 16.55, 3, '1/28/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (8, 49.29, 4, '1/3/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (9, 36.8, 3, '1/19/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (10, 19.99, 4, '1/2/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (11, 49.21, 4, '1/8/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (12, 10.14, 3, '1/12/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (13, 39.66, 4, '1/15/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (14, 44.15, 4, '1/29/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (15, 30.83, 3, '1/27/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (16, 40.02, 4, '1/7/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (17, 35.41, 4, '1/10/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (18, 23.39, 4, '1/17/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (19, 34.48, 4, '1/6/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (20, 34.51, 3, '1/3/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (21, 18.19, 3, '1/9/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (22, 17.89, 3, '1/28/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (23, 27.16, 3, '1/4/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (24, 18.46, 4, '1/2/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (25, 29.69, 4, '1/22/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (26, 24.77, 3, '1/23/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (27, 25.6, 3, '1/7/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (28, 12.64, 4, '1/28/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (29, 38.92, 4, '1/21/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (30, 27.79, 3, '1/26/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (31, 44.77, 3, '1/26/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (32, 32.93, 4, '1/25/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (33, 20.76, 3, '1/18/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (34, 25.3, 3, '1/7/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (35, 18.79, 3, '1/24/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (36, 45.3, 4, '1/24/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (37, 14.78, 4, '1/1/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (38, 15.6, 3, '1/26/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (39, 12.81, 3, '1/3/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (40, 27.73, 4, '1/20/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (41, 31.68, 4, '1/12/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (42, 39.51, 4, '1/24/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (43, 24.63, 4, '1/14/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (44, 24.3, 4, '1/2/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (45, 18.95, 3, '1/3/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (46, 32.71, 4, '1/6/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (47, 34.74, 4, '1/16/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (48, 14.8, 4, '1/24/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (49, 28.65, 4, '1/19/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (50, 44.16, 4, '1/21/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (51, 15.28, 3, '1/14/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (52, 25.79, 3, '1/7/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (53, 14.26, 4, '1/1/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (54, 34.92, 3, '1/23/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (55, 16.04, 4, '1/4/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (56, 42.14, 4, '1/5/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (57, 39.52, 4, '1/27/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (58, 49.01, 3, '1/7/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (59, 49.4, 3, '1/22/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (60, 28.43, 3, '1/24/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (61, 29.54, 3, '1/24/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (62, 35.06, 4, '1/17/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (63, 15.39, 4, '1/18/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (64, 12.76, 4, '1/16/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (65, 36.22, 3, '1/18/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (1, 23.64, 4, '1/22/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (2, 45.78, 3, '1/27/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (3, 22.28, 3, '1/3/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (4, 17.23, 3, '1/24/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (5, 17.7, 3, '1/26/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (6, 42.34, 3, '1/13/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (7, 12.58, 3, '1/7/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (8, 47.88, 4, '1/25/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (9, 21.72, 3, '1/22/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (10, 40.84, 4, '1/23/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (11, 35.52, 4, '1/11/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (12, 38.78, 4, '1/16/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (13, 15.08, 3, '1/17/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (14, 48.17, 4, '1/21/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (15, 14.0, 3, '1/3/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (16, 44.41, 4, '1/8/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (17, 25.23, 4, '1/21/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (18, 12.88, 3, '1/20/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (19, 42.96, 4, '1/27/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (20, 23.88, 3, '1/28/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (21, 19.81, 4, '1/8/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (22, 27.31, 3, '1/16/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (23, 14.61, 3, '1/11/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (24, 44.41, 3, '1/15/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (25, 15.4, 4, '1/23/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (26, 49.29, 3, '1/12/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (27, 44.23, 3, '1/8/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (28, 17.41, 3, '1/19/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (29, 38.36, 4, '1/26/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (30, 29.79, 4, '1/6/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (31, 31.03, 3, '1/20/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (32, 45.44, 4, '1/1/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (33, 25.07, 3, '1/6/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (34, 44.88, 3, '1/1/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (35, 17.67, 4, '1/26/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (36, 34.46, 4, '1/17/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (37, 11.74, 4, '1/5/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (38, 24.77, 3, '1/10/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (39, 11.36, 4, '1/22/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (40, 32.49, 3, '1/25/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (41, 49.34, 3, '1/10/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (42, 24.25, 4, '1/29/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (43, 45.48, 4, '1/2/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (44, 14.97, 4, '1/28/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (45, 17.51, 3, '1/24/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (46, 15.81, 3, '1/25/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (47, 29.64, 3, '1/7/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (48, 43.26, 3, '1/22/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (49, 44.54, 3, '1/16/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (50, 40.45, 3, '1/7/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (51, 21.63, 3, '1/21/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (52, 36.95, 4, '1/3/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (53, 10.56, 4, '1/3/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (54, 41.33, 3, '1/2/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (55, 31.07, 3, '1/22/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (56, 15.6, 3, '1/21/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (57, 12.87, 3, '1/26/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (58, 42.73, 4, '1/12/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (59, 23.2, 3, '1/2/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (60, 31.17, 3, '1/18/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (61, 24.49, 4, '1/26/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (62, 45.21, 4, '1/15/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (63, 33.78, 4, '1/13/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (64, 29.64, 4, '1/20/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (65, 33.64, 4, '1/13/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (1, 38.53, 3, '1/11/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (2, 30.93, 4, '1/9/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (3, 21.6, 3, '1/26/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (4, 15.15, 3, '1/14/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (5, 14.66, 4, '1/7/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (6, 44.21, 3, '1/21/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (7, 47.88, 4, '1/17/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (8, 20.99, 3, '1/20/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (9, 34.26, 3, '1/17/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (10, 28.71, 4, '1/6/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (11, 28.89, 3, '1/7/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (12, 39.14, 4, '1/8/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (13, 33.61, 4, '1/19/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (14, 43.1, 3, '1/28/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (15, 26.0, 3, '1/2/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (16, 22.32, 3, '1/21/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (17, 28.28, 3, '1/15/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (18, 39.32, 4, '1/4/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (19, 26.42, 4, '1/22/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (20, 47.62, 3, '1/17/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (21, 33.42, 3, '1/3/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (22, 40.45, 4, '1/13/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (23, 42.94, 3, '1/18/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (24, 19.77, 4, '1/16/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (25, 46.65, 4, '1/9/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (26, 49.68, 3, '1/29/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (27, 17.81, 3, '1/21/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (28, 21.42, 4, '1/2/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (29, 47.07, 3, '1/4/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (30, 27.13, 3, '1/22/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (31, 38.76, 3, '1/14/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (32, 26.78, 4, '1/8/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (33, 18.98, 3, '1/13/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (34, 48.12, 4, '1/28/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (35, 25.45, 4, '1/21/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (36, 13.26, 3, '1/24/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (37, 14.78, 4, '1/27/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (38, 37.44, 3, '1/10/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (39, 29.71, 4, '1/7/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (40, 33.87, 3, '1/24/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (41, 31.96, 4, '1/6/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (42, 26.09, 4, '1/7/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (43, 21.41, 3, '1/6/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (44, 28.79, 4, '1/21/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (45, 35.88, 4, '1/5/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (46, 44.89, 3, '1/26/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (47, 41.86, 4, '1/15/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (48, 13.07, 3, '1/20/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (49, 33.4, 4, '1/12/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (50, 38.45, 3, '1/26/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (51, 11.62, 4, '1/24/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (52, 46.23, 4, '1/14/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (53, 31.52, 4, '1/26/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (54, 31.14, 3, '1/20/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (55, 15.24, 3, '1/20/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (56, 39.59, 3, '1/28/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (57, 45.51, 4, '1/18/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (58, 40.99, 4, '1/14/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (59, 12.09, 4, '1/17/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (60, 36.81, 3, '1/20/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (61, 30.64, 4, '1/26/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (62, 45.83, 3, '1/26/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (63, 49.24, 4, '1/4/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (64, 34.88, 4, '1/12/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (65, 21.12, 3, '1/5/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (1, 16.96, 4, '1/4/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (2, 18.29, 4, '1/4/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (3, 19.53, 4, '1/11/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (4, 11.3, 4, '1/25/2020');
insert into Medicine (type_id, quantity, m_unit_id, purchase_date) values (5, 10.97, 3, '1/22/2020');




-- ProductType
insert into ProductType (item_id, name) values (16, 'MILK');
insert into ProductType (item_id, name) values (17, 'MEAT');


SELECT * FROM Unit
SELECT * FROM ItemID
SELECT * FROM Sales
